# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Aurelitec.Thumbico
PackageVersion: 1.5.0.25
PackageLocale: en-US
Publisher: Aurelitec
PackageName: Thumbico
License: MIT-Lizenz
Copyright: Copyright © 2011-2015 Aurelitec (http://www.aurelitec.com)
ShortDescription: Thumbico Installer
ManifestType: defaultLocale
ManifestVersion: 1.6.0
